server:
    port: 7777
spring:
    redis:
        host: 192.168.6.222  # 地址
        port: 6379  # 端口号
        password: 123456
        database: 0  # 数据库索引（默认为0）
        timeout: 1800000  # 连接超时时间（毫秒）
        lettuce:
            pool:
                max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1  # 最大阻塞等待时间（负数表示没有限制）
                max-idle: 5  # 连接池中最大空闲连接
                min-idle: 0  # 连接池中最小空闲连接
    datasource:
        url: jdbc:mysql://192.168.6.222:3306/fugitive_info?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root

logging:
    level:
        com.itheima: debug
    pattern:
        dateformat: HH:mm:ss